### ISSUE TITLE
Results for DINO v2?

### ISSUE THREAD

**Issue by pulkitkumar95** [QUVA-Lab/SIGMA#1]
Hey,

First of all great work! I noticed in the code that dino v2 protector has also been implemented. I was wondering do you have the results for it? 

Thanks!

**Comment by SMSD75** [comment]
Hi, 
Thank you for your interest in our research. Yeah, we tested both DINOv2 and DINOv1 and realized that DINOv1 works slightly better than DINOv2. But you can go ahead and train the model ;)
